# Generated by Django 4.1.3 on 2022-11-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='created_at',
            new_name='time_task_created',
        ),
    ]
