# Generated by Django 4.1.3 on 2022-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0002_rename_created_at_list_time_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='task',
            field=models.CharField(max_length=200),
        ),
    ]
