# Generated by Django 4.1.3 on 2022-11-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0003_alter_list_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='time_task_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
